# Generated by Django 5.0.4 on 2024-04-12 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='nota',
        ),
    ]
