# Generated by Django 5.0.4 on 2024-04-12 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_remove_cursos_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='estudiante.cursos'),
        ),
    ]
